trigger:
  branches:
    include:
      - devops

jobs:
- job: BuildSolutionOnPullRequest
  displayName: 'Build solution on pull request'
  steps:
  - checkout: self
    displayName: 'Checkout source code'
  - script: echo "Build solution on pull request"
  
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 8.x'
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore $(Build.SourcesDirectory)/api/NeededApi.sln
    displayName: 'Restore packages' 

  - script: dotnet test $(Build.SourcesDirectory)/tests/NeededApi.Tests.csproj
    displayName: 'Run tests'

  - script: dotnet build $(Build.SourcesDirectory)/api/NeededApi.sln
    displayName: 'Build solution'

  - script: echo "Build solution on pull request completed"