# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "devops" ]
  pull_request:
    branches: [ "devops" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore api/NeededApi.csproj
    - name: Build
      run: dotnet build --no-restore api/NeededApi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal tests/NeededApi.Tests.csproj
    - name: Print message
      run: echo "restore, build and test done"
